name: Build

on:
  workflow_dispatch:

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ~1.19.6


      #Need to install rpm so ubuntu can make rpm by default ubuntu can make deb
      - name: Install rpm
        run: sudo apt install rpm

      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'
      - name: build
        run: make build
      - name: package
        run: make package-deb 
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/*.deb
          tag_name: ${{ github.ref }}
          body: |
            ${{ github.event.inputs.body }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}